--------------

apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
  labels:
    app: httpd_app
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80

create http-pod : kubectl apply -f httpd-pod.yaml
kubectl get pods -l app=httpd_app
---------------------------------
